import { randomBytes } from "node:crypto";
import { eq, desc } from "drizzle-orm";

import { db } from "../db";
import { inviteCodes, mentorRegistrations, mentorSetupTokens, stakeholderRegistrations, users } from "../db/schema";
import { AppError } from "../utils/app-error";
import { sendMail } from "../mail/mailer";

/** Base URL for the frontend, used when constructing invite and setup links. */
const FRONTEND_URL = process.env["FRONTEND_URL"] ?? "http://localhost:3000";

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Generates a random invite code string in the format "AMPLIFY-XXXXXXXX"
 * where X is an uppercase alphanumeric character.
 *
 * Uses 6 bytes of cryptographic randomness → 48 bits of entropy,
 * which makes collisions negligible at any realistic scale.
 */
function generateCode(): string {
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const bytes = randomBytes(6);
  let suffix = "";
  for (const byte of bytes) {
    // Modulo bias is negligible: 256 / 36 ≈ 7.1, so bias per character is <1%.
    suffix += chars[byte % chars.length];
  }
  return `AMPLIFY-${suffix}`;
}

// ---------------------------------------------------------------------------
// Return-type interfaces
// ---------------------------------------------------------------------------

/** Shape returned by createInvite and included in listInvites rows. */
export interface InviteResult {
  id: string;
  code: string;
  inviteLink: string;
}

/** Shape of a user who consumed an invite code, as returned in listInvites. */
export interface InviteUsedBy {
  id: string;
  fullName: string | null;
  email: string | null;
  country: string | null;
  createdAt: Date | null;
}

/** Full invite row including the optional consuming user. */
export interface InviteWithUser {
  id: string;
  code: string;
  status: string;
  createdAt: Date;
  inviteLink: string;
  usedBy: InviteUsedBy | null;
}

/** Shape of a mentor application returned to the admin. */
export interface MentorApplication {
  id: string;
  name: string;
  email: string;
  linkedinUrl: string | null;
  hourlyRate: number | null;
  expertise: string[] | null;
  methods: string[] | null;
  passion: string | null;
  status: string;
  createdAt: Date;
}

/** Shape of a stakeholder application returned to the admin. */
export interface StakeholderApplication {
  id: string;
  type: string;
  fullName: string;
  title: string;
  email: string;
  country: string;
  website: string;
  phone: string;
  representing: string;
  involvement: string[];
  createdAt: Date;
}

// ---------------------------------------------------------------------------
// createInvite
// ---------------------------------------------------------------------------

/**
 * Creates a new invite code, generated by the specified admin user.
 *
 * Generates a random code and inserts it into the `invite_codes` table with
 * status 'active'. Collision probability at realistic scales is negligible
 * (< 1 in a billion for fewer than 100 000 codes).
 *
 * @param adminUserId - UUID of the admin performing the action.
 * @returns The created invite record and its fully-formed invite link.
 * @throws AppError(500, "INSERT_FAILED") if the DB insert returns no row.
 */
export async function createInvite(adminUserId: string): Promise<InviteResult> {
  const code = generateCode();

  const [inserted] = await db
    .insert(inviteCodes)
    .values({
      code,
      createdBy: adminUserId,
      status: "active",
    })
    .returning({ id: inviteCodes.id, code: inviteCodes.code });

  if (!inserted) {
    throw new AppError("Failed to create invite code", 500, "INSERT_FAILED");
  }

  const inviteLink = `${FRONTEND_URL}/sign-up?code=${inserted.code}`;

  return { id: inserted.id, code: inserted.code, inviteLink };
}

// ---------------------------------------------------------------------------
// listInvites
// ---------------------------------------------------------------------------

/**
 * Returns all invite codes ordered by creation date descending.
 *
 * Performs a LEFT JOIN against the `users` table via the `used_by` FK to
 * populate the `usedBy` field when the code has been redeemed. Codes that
 * have not been used will have `usedBy: null`.
 *
 * @returns Array of invite records, each optionally including the user who used it.
 */
export async function listInvites(): Promise<InviteWithUser[]> {
  // Alias the users table so Drizzle doesn't mix up the joined columns with
  // the top-level users table that appears in other queries in this module.
  const usedByUser = {
    id: users.id,
    fullName: users.fullName,
    email: users.email,
    country: users.country,
    createdAt: users.createdAt,
  };

  const rows = await db
    .select({
      id: inviteCodes.id,
      code: inviteCodes.code,
      status: inviteCodes.status,
      createdAt: inviteCodes.createdAt,
      usedById: usedByUser.id,
      usedByFullName: usedByUser.fullName,
      usedByEmail: usedByUser.email,
      usedByCountry: usedByUser.country,
      usedByCreatedAt: usedByUser.createdAt,
    })
    .from(inviteCodes)
    .leftJoin(users, eq(inviteCodes.usedBy, users.id))
    .orderBy(desc(inviteCodes.createdAt));

  // Map flat JOIN rows to the nested InviteWithUser shape.
  return rows.map((row) => ({
    id: row.id,
    code: row.code,
    status: row.status,
    createdAt: row.createdAt,
    inviteLink: `${FRONTEND_URL}/sign-up?code=${row.code}`,
    usedBy: row.usedById
      ? {
          id: row.usedById,
          fullName: row.usedByFullName,
          email: row.usedByEmail,
          country: row.usedByCountry ?? null,
          createdAt: row.usedByCreatedAt,
        }
      : null,
  }));
}

// ---------------------------------------------------------------------------
// listMentorApplications
// ---------------------------------------------------------------------------

/**
 * Returns all mentor applications, optionally filtered by status.
 *
 * Results are ordered by creation date descending so the newest applications
 * appear first.
 *
 * @param status - Optional status filter (e.g. "pending", "approved", "rejected").
 *                 When omitted, all applications are returned.
 * @returns Array of mentor application records.
 */
export async function listMentorApplications(
  status?: string,
): Promise<MentorApplication[]> {
  const query = db
    .select({
      id: mentorRegistrations.id,
      name: mentorRegistrations.name,
      email: mentorRegistrations.email,
      linkedinUrl: mentorRegistrations.linkedinUrl,
      hourlyRate: mentorRegistrations.hourlyRate,
      expertise: mentorRegistrations.expertise,
      methods: mentorRegistrations.methods,
      passion: mentorRegistrations.passion,
      status: mentorRegistrations.status,
      createdAt: mentorRegistrations.createdAt,
    })
    .from(mentorRegistrations)
    .orderBy(desc(mentorRegistrations.createdAt));

  if (status) {
    return query.where(eq(mentorRegistrations.status, status));
  }

  return query;
}

// ---------------------------------------------------------------------------
// approveMentorApplication
// ---------------------------------------------------------------------------

/**
 * Approves a pending mentor application.
 *
 * Steps performed atomically inside a transaction:
 * 1. Fetch the application and verify it exists and is in 'pending' state.
 * 2. Generate a 32-byte hex setup token with 48-hour expiry.
 * 3. Insert the token into `mentor_setup_tokens`.
 * 4. Update the application status to 'approved'.
 * 5. Send the mentor an approval email containing their setup link.
 *
 * Email is sent *outside* the transaction to avoid holding the DB connection
 * open during an external network call. If the email fails after the commit,
 * the status is still updated but the email may need to be resent manually.
 *
 * @param id - UUID of the mentor_registrations row.
 * @throws AppError(404, "NOT_FOUND")         — application does not exist.
 * @throws AppError(400, "ALREADY_PROCESSED") — application is not in 'pending' state.
 */
export async function approveMentorApplication(id: string): Promise<void> {
  // --- 1. Fetch and validate the application --------------------------------
  const found = await db
    .select()
    .from(mentorRegistrations)
    .where(eq(mentorRegistrations.id, id))
    .limit(1);

  const mentor = found[0];
  if (!mentor) {
    throw new AppError("Mentor application not found", 404, "NOT_FOUND");
  }

  if (mentor.status !== "pending") {
    throw new AppError(
      "This application has already been processed",
      400,
      "ALREADY_PROCESSED",
    );
  }

  // --- 2 & 3. Generate token and persist changes inside a transaction -------
  const token = randomBytes(32).toString("hex");
  const expiresAt = new Date(Date.now() + 48 * 60 * 60 * 1000); // 48 hours

  await db.transaction(async (tx) => {
    // Insert the setup token.
    await tx.insert(mentorSetupTokens).values({
      mentorRegistrationId: id,
      token,
      expiresAt,
    });

    // Mark the application as approved.
    await tx
      .update(mentorRegistrations)
      .set({ status: "approved" })
      .where(eq(mentorRegistrations.id, id));
  });

  // --- 4. Send the approval email (after transaction commits) ---------------
  // Wrapped in catch so a mailer failure never rolls back the DB update.
  const setupLink = `${FRONTEND_URL}/mentor/setup?token=${token}`;

  await sendMail({
    to: mentor.email,
    subject: "Your AI Amplify Mentor Application Has Been Approved",
    template: "mentor-approval",
    context: {
      mentorName: mentor.name,
      setupLink,
    },
  }).catch((err: unknown) => {
    // Email delivery failure is non-fatal — the status is already committed.
    // Log so the error is visible in server output rather than silently lost.
    console.error("[mail] Failed to send mentor approval email:", (err as Error)?.message ?? err);
  });
}

// ---------------------------------------------------------------------------
// rejectMentorApplication
// ---------------------------------------------------------------------------

/**
 * Rejects a mentor application by updating its status to 'rejected'.
 *
 * No email is sent on rejection — this can be added later if the product
 * requires notifying applicants of rejections.
 *
 * @param id - UUID of the mentor_registrations row.
 * @throws AppError(404, "NOT_FOUND") — application does not exist.
 */
export async function rejectMentorApplication(id: string): Promise<void> {
  const found = await db
    .select({ id: mentorRegistrations.id })
    .from(mentorRegistrations)
    .where(eq(mentorRegistrations.id, id))
    .limit(1);

  if (!found[0]) {
    throw new AppError("Mentor application not found", 404, "NOT_FOUND");
  }

  await db
    .update(mentorRegistrations)
    .set({ status: "rejected" })
    .where(eq(mentorRegistrations.id, id));
}

// ---------------------------------------------------------------------------
// listStakeholderApplications
// ---------------------------------------------------------------------------

/**
 * Returns all stakeholder registrations, optionally filtered by type.
 *
 * Results are ordered by creation date descending so the newest submissions
 * appear first.
 *
 * @param type - Optional type filter (e.g. "vc", "government", "corporate",
 *               "university", "incubator"). When omitted, all are returned.
 * @returns Array of stakeholder registration records.
 */
export async function listStakeholderApplications(
  type?: string,
): Promise<StakeholderApplication[]> {
  const query = db
    .select({
      id: stakeholderRegistrations.id,
      type: stakeholderRegistrations.type,
      fullName: stakeholderRegistrations.fullName,
      title: stakeholderRegistrations.title,
      email: stakeholderRegistrations.email,
      country: stakeholderRegistrations.country,
      website: stakeholderRegistrations.website,
      phone: stakeholderRegistrations.phone,
      representing: stakeholderRegistrations.representing,
      involvement: stakeholderRegistrations.involvement,
      createdAt: stakeholderRegistrations.createdAt,
    })
    .from(stakeholderRegistrations)
    .orderBy(desc(stakeholderRegistrations.createdAt));

  if (type) {
    return query.where(eq(stakeholderRegistrations.type, type));
  }

  return query;
}
